services:
  db:
    container_name: forms-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forms
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: